inherit_from: .rubocop_todo.yml

Style/EmptyCaseCondition:
  Enabled: false

Style/FormatStringToken:
  EnforcedStyle: template

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: consistent_comma

Metrics/LineLength:
  Max: 124
  AllowURI: true
  URISchemes:
    - http
    - https
